class PlanetCard {
  final String id;
  final String title;
  final String category;
  final String imageAsset;
  final String petVoice;
  final String knowledgePoint;
  final String source;

  const PlanetCard({
    required this.id,
    required this.title,
    required this.category,
    required this.imageAsset,
    required this.petVoice,
    required this.knowledgePoint,
    required this.source,
  });
}

const planetCards = <PlanetCard>[
  PlanetCard(
    id: '001',
    title: '等我靠近',
    category: '互動與界線',
    imageAsset: 'assets/cards/001-approach-v4.png',
    petVoice: '給我一點空間，讓我自己走近你。',
    knowledgePoint: '尊重貓咪的距離，讓牠選擇是否互動。',
    source: '《貓邏輯》Q25：主動靠近與保持距離（第 174 頁），依知識庫摘要改寫。',
  ),
  PlanetCard(
    id: '002',
    title: '伸個懶腰',
    category: '抓磨與環境',
    imageAsset: 'assets/cards/002-stretch.png',
    petVoice: '讓我伸展一下，也磨磨爪子。',
    knowledgePoint: '提供穩固抓柱，讓貓咪自在伸展身體。',
    source: '《貓邏輯》第二章：選貓抓柱（第 102–107 頁），依知識庫摘要改寫。',
  ),
  PlanetCard(
    id: '003',
    title: '我的小角落',
    category: '安心與休息',
    imageAsset: 'assets/cards/003-quiet-corner.png',
    petVoice: '讓我在這裡，安靜休息一下。',
    knowledgePoint: '提供藏身處，保留不被打擾的休息空間。',
    source: '《貓邏輯》活動空間相關內容，依知識庫「生活配置」摘要改寫。',
  ),
  PlanetCard(
    id: '004',
    title: '先熟悉，再出發',
    category: '外出籠適應',
    imageAsset: 'assets/cards/004-carrier.png',
    petVoice: '讓我先聞一聞，再慢慢走進去。',
    knowledgePoint: '平日開放外出籠，讓貓咪自願探索與進入。',
    source: '《貓邏輯》Q17：外出籠，依知識庫摘要改寫。開放籠門適用於居家適應；運輸時須關妥並固定。',
  ),
  PlanetCard(
    id: '005',
    title: '玩具才是獵物',
    category: '遊戲與陪伴',
    imageAsset: 'assets/cards/005-play-with-toys.png',
    petVoice: '陪我追追玩具，再讓我抓到它。',
    knowledgePoint: '用玩具陪貓咪玩，不把手腳當獵物。',
    source: '《貓邏輯》遊戲相關內容，依知識庫摘要改寫。線繩玩具需有人監督，用後收妥。',
  ),
  PlanetCard(
    id: '006',
    title: '各自的小餐桌',
    category: '多貓與資源',
    imageAsset: 'assets/cards/006-separate-meals.png',
    petVoice: '有自己的位置，我想慢慢吃。',
    knowledgePoint: '分開安排用餐位置，讓每隻貓都能自在進食。',
    source: '《貓邏輯》多貓相關內容，依知識庫「資源分散」摘要改寫。',
  ),
  PlanetCard(
    id: '007',
    title: '一步一步上去',
    category: '動線與照護',
    imageAsset: 'assets/cards/007-gentle-steps.png',
    petVoice: '有了小階梯，我可以慢慢上去。',
    knowledgePoint: '設置穩固階梯與防滑面，配合貓咪的行動能力。',
    source: '《貓邏輯》活動空間與高齡相關內容，依知識庫「生活配置／高齡適應」摘要改寫。',
  ),
  PlanetCard(
    id: '008',
    title: '乾淨的小廁所',
    category: '貓砂與清潔',
    imageAsset: 'assets/cards/008-clean-litter.png',
    petVoice: '我想要乾淨、舒服的如廁空間。',
    knowledgePoint: '每天清除排泄物，不靠香味掩蓋髒污。',
    source: '《貓邏輯》貓砂清潔相關內容，依知識庫「貓砂配置」摘要改寫。',
  ),
  PlanetCard(
    id: '009',
    title: '做到了，我很棒',
    category: '學習與獎勵',
    imageAsset: 'assets/cards/009-gentle-reward-v3.png',
    petVoice: '陪我慢慢練習，適時給予鼓勵。',
    knowledgePoint: '把練習拆成小步驟，及時獎勵自願的動作。',
    source: '《貓邏輯》獎勵與訓練相關內容，依知識庫「練習」摘要改寫。練習保持短時間、能退出，不以挨餓換取服從。',
  ),
  PlanetCard(
    id: '010',
    title: '摸摸先暫停',
    category: '撫摸與訊號',
    imageAsset: 'assets/cards/010-pause-petting-v3.png',
    petVoice: '先停一下，讓我自在待一會兒。',
    knowledgePoint: '留意甩尾、耳朵後移等訊號，提早暫停撫摸。',
    source: '《貓邏輯》撫摸與互動相關內容，依知識庫「情境判斷」摘要改寫。需結合當時情境觀察，不以單一訊號判定情緒。',
  ),
  PlanetCard(
    id: '011',
    title: '慢慢認識你',
    category: '新貓與引介',
    imageAsset: 'assets/cards/011-gradual-introduction.png',
    petVoice: '給我一點時間，慢慢認識新朋友。',
    knowledgePoint: '先分隔，再循序引介，依貓咪的反應調整步調。',
    source: '《貓邏輯》多貓相關內容，依知識庫「漸進引介」摘要改寫。圖示為隔障看見階段；以能放鬆、能退出為進度依據，緊張升高就退回前一步。',
  ),
  PlanetCard(
    id: '012',
    title: '有人來看我',
    category: '外出與照護',
    imageAsset: 'assets/cards/012-daily-visit.png',
    petVoice: '你不在家時，也想有人來看看我。',
    knowledgePoint: '外出過夜時，安排可信任的人每日實際探視。',
    source: '《貓邏輯》外出過夜相關內容，依知識庫摘要改寫。至少每日實際探視；幼貓、病貓或需用藥者提高頻率，自動設備不能取代全部照護。',
  ),
  PlanetCard(
    id: '013',
    title: '窗邊看世界',
    category: '窗景與安全',
    imageAsset: 'assets/cards/013-safe-window-v2.png',
    petVoice: '我想待在窗邊，看看外面的世界。',
    knowledgePoint: '窗邊設置牢固防逃設施，讓貓咪安全欣賞窗景。',
    source: '《貓邏輯》活動空間相關內容，依知識庫「生活配置」摘要改寫。圖面為防逃設施示意，實際需確認固定與完整性。',
  ),
  PlanetCard(
    id: '014',
    title: '小東西收好',
    category: '居家與安全',
    imageAsset: 'assets/cards/014-store-small-items.png',
    petVoice: '我會好奇，請幫我把小東西收好。',
    knowledgePoint: '收好線材、橡皮筋等小物，減少貓咪誤食的機會。',
    source: '《貓邏輯》危險物品相關內容，依知識庫「環境管理」摘要改寫。',
  ),
  PlanetCard(
    id: '015',
    title: '記下我的日常',
    category: '觀察與紀錄',
    imageAsset: 'assets/cards/015-daily-observation.png',
    petVoice: '多留意我的日常，慢慢更懂我。',
    knowledgePoint: '記錄飲食、排泄與活動，留意和平常不同的變化。',
    source: '《貓邏輯》個別健康觀察相關內容，依知識庫「日常基線」摘要改寫。',
  ),
  PlanetCard(
    id: '016',
    title: '一起學會溫柔',
    category: '孩子與互動',
    imageAsset: 'assets/cards/016-gentle-together.png',
    petVoice: '慢慢陪我就好，讓我自在走動。',
    knowledgePoint: '孩子與貓咪互動時，由成人在旁引導，不追逐或強抱。',
    source: '《貓邏輯》兒童互動相關內容，依知識庫「兒童與來客」摘要改寫。成人需主動監督，並保留貓咪可退回、不被孩子打擾的區域。',
  ),
  PlanetCard(
    id: '017',
    title: '找找小點心',
    category: '尋食與探索',
    imageAsset: 'assets/cards/017-gentle-foraging-v2.png',
    petVoice: '讓我聞一聞，找找藏好的小點心。',
    knowledgePoint: '提供安全、容易上手的尋食活動，依反應調整難度並保留休息。',
    source: '《貓邏輯》遊戲與環境相關內容，依知識庫「安全尋食」摘要改寫。',
  ),
  PlanetCard(
    id: '018',
    title: '轉身也自在',
    category: '貓砂與空間',
    imageAsset: 'assets/cards/018-room-to-turn.png',
    petVoice: '給我寬敞一點，轉身也能自在。',
    knowledgePoint: '選擇大小合適的貓砂盆，讓貓咪能輕鬆轉身。',
    source: '《貓邏輯》貓砂配置相關內容，依知識庫摘要改寫。盆長約鼻端至尾根長度的 1.5 倍，並依個體偏好選擇盆型。',
  ),
  PlanetCard(
    id: '019',
    title: '玩完收起來',
    category: '玩具與收納',
    imageAsset: 'assets/cards/019-store-after-play.png',
    petVoice: '今天先玩到這裡，下次再陪我玩。',
    knowledgePoint: '線繩玩具需有人監督，玩完收妥，避免自行啃咬。',
    source: '《貓邏輯》遊戲與環境相關內容，依知識庫「線繩玩具有人監督，用後收妥」摘要改寫。',
  ),
  PlanetCard(
    id: '020',
    title: '看看我的小肚肚',
    category: '肢體與界線',
    imageAsset: 'assets/cards/020-belly-boundaries.png',
    petVoice: '陪我躺一下，先別急著摸肚肚。',
    knowledgePoint: '翻肚不代表同意摸肚子，尊重貓咪的選擇與界線。',
    source: '《貓邏輯》個體選擇與身體訊號相關內容，依知識庫「翻肚不是摸肚許可」摘要改寫。',
  ),
];
