class PlanetCard {
  final String id;
  final String title;
  final String category;
  final String imageAsset;
  final String petVoice;
  final String knowledgePoint;
  final String source;

  const PlanetCard({
    required this.id,
    required this.title,
    required this.category,
    required this.imageAsset,
    required this.petVoice,
    required this.knowledgePoint,
    required this.source,
  });
}

const planetCards = <PlanetCard>[
  PlanetCard(
    id: '001',
    title: '等我靠近',
    category: '互動與界線',
    imageAsset: 'assets/cards/001-approach-v4.png',
    petVoice: '給我一點空間，讓我自己走近你。',
    knowledgePoint: '尊重貓咪的距離，讓牠選擇是否互動。',
    source: '《貓邏輯》Q25：主動靠近與保持距離（第 174 頁），依知識庫摘要改寫。',
  ),
  PlanetCard(
    id: '002',
    title: '伸個懶腰',
    category: '抓磨與環境',
    imageAsset: 'assets/cards/002-stretch.png',
    petVoice: '讓我伸展一下，也磨磨爪子。',
    knowledgePoint: '提供穩固抓柱，讓貓咪自在伸展身體。',
    source: '《貓邏輯》第二章：選貓抓柱（第 102–107 頁），依知識庫摘要改寫。',
  ),
  PlanetCard(
    id: '003',
    title: '我的小角落',
    category: '安心與休息',
    imageAsset: 'assets/cards/003-quiet-corner.png',
    petVoice: '讓我在這裡，安靜休息一下。',
    knowledgePoint: '提供藏身處，保留不被打擾的休息空間。',
    source: '《貓邏輯》活動空間相關內容，依知識庫「生活配置」摘要改寫。',
  ),
  PlanetCard(
    id: '004',
    title: '先熟悉，再出發',
    category: '外出籠適應',
    imageAsset: 'assets/cards/004-carrier.png',
    petVoice: '讓我先聞一聞，再慢慢走進去。',
    knowledgePoint: '平日開放外出籠，讓貓咪自願探索與進入。',
    source: '《貓邏輯》Q17：外出籠，依知識庫摘要改寫。開放籠門適用於居家適應；運輸時須關妥並固定。',
  ),
  PlanetCard(
    id: '005',
    title: '玩具才是獵物',
    category: '遊戲與陪伴',
    imageAsset: 'assets/cards/005-play-with-toys.png',
    petVoice: '陪我追追玩具，再讓我抓到它。',
    knowledgePoint: '用玩具陪貓咪玩，不把手腳當獵物。',
    source: '《貓邏輯》遊戲相關內容，依知識庫摘要改寫。線繩玩具需有人監督，用後收妥。',
  ),
  PlanetCard(
    id: '006',
    title: '各自的小餐桌',
    category: '多貓與資源',
    imageAsset: 'assets/cards/006-separate-meals.png',
    petVoice: '有自己的位置，我想慢慢吃。',
    knowledgePoint: '分開安排用餐位置，讓每隻貓都能自在進食。',
    source: '《貓邏輯》多貓相關內容，依知識庫「資源分散」摘要改寫。',
  ),
  PlanetCard(
    id: '007',
    title: '一步一步上去',
    category: '動線與照護',
    imageAsset: 'assets/cards/007-gentle-steps.png',
    petVoice: '有了小階梯，我可以慢慢上去。',
    knowledgePoint: '設置穩固階梯與防滑面，配合貓咪的行動能力。',
    source: '《貓邏輯》活動空間與高齡相關內容，依知識庫「生活配置／高齡適應」摘要改寫。',
  ),
  PlanetCard(
    id: '008',
    title: '乾淨的小廁所',
    category: '貓砂與清潔',
    imageAsset: 'assets/cards/008-clean-litter.png',
    petVoice: '我想要乾淨、舒服的如廁空間。',
    knowledgePoint: '每天清除排泄物，不靠香味掩蓋髒污。',
    source: '《貓邏輯》貓砂清潔相關內容，依知識庫「貓砂配置」摘要改寫。',
  ),
  PlanetCard(
    id: '009',
    title: '做到了，我很棒',
    category: '學習與獎勵',
    imageAsset: 'assets/cards/009-gentle-reward-v3.png',
    petVoice: '陪我慢慢練習，適時給予鼓勵。',
    knowledgePoint: '把練習拆成小步驟，及時獎勵自願的動作。',
    source: '《貓邏輯》獎勵與訓練相關內容，依知識庫「練習」摘要改寫。練習保持短時間、能退出，不以挨餓換取服從。',
  ),
  PlanetCard(
    id: '010',
    title: '摸摸先暫停',
    category: '撫摸與訊號',
    imageAsset: 'assets/cards/010-pause-petting-v3.png',
    petVoice: '先停一下，讓我自在待一會兒。',
    knowledgePoint: '留意甩尾、耳朵後移等訊號，提早暫停撫摸。',
    source: '《貓邏輯》撫摸與互動相關內容，依知識庫「情境判斷」摘要改寫。需結合當時情境觀察，不以單一訊號判定情緒。',
  ),
  PlanetCard(
    id: '011',
    title: '慢慢認識你',
    category: '新貓與引介',
    imageAsset: 'assets/cards/011-gradual-introduction.png',
    petVoice: '給我一點時間，慢慢認識新朋友。',
    knowledgePoint: '先分隔，再循序引介，依貓咪的反應調整步調。',
    source: '《貓邏輯》多貓相關內容，依知識庫「漸進引介」摘要改寫。圖示為隔障看見階段；以能放鬆、能退出為進度依據，緊張升高就退回前一步。',
  ),
  PlanetCard(
    id: '012',
    title: '有人來看我',
    category: '外出與照護',
    imageAsset: 'assets/cards/012-daily-visit.png',
    petVoice: '你不在家時，也想有人來看看我。',
    knowledgePoint: '外出過夜時，安排可信任的人每日實際探視。',
    source: '《貓邏輯》外出過夜相關內容，依知識庫摘要改寫。至少每日實際探視；幼貓、病貓或需用藥者提高頻率，自動設備不能取代全部照護。',
  ),
  PlanetCard(
    id: '013',
    title: '窗邊看世界',
    category: '窗景與安全',
    imageAsset: 'assets/cards/013-safe-window-v2.png',
    petVoice: '我想待在窗邊，看看外面的世界。',
    knowledgePoint: '窗邊設置牢固防逃設施，讓貓咪安全欣賞窗景。',
    source: '《貓邏輯》活動空間相關內容，依知識庫「生活配置」摘要改寫。圖面為防逃設施示意，實際需確認固定與完整性。',
  ),
  PlanetCard(
    id: '014',
    title: '小東西收好',
    category: '居家與安全',
    imageAsset: 'assets/cards/014-store-small-items.png',
    petVoice: '我會好奇，請幫我把小東西收好。',
    knowledgePoint: '收好線材、橡皮筋等小物，減少貓咪誤食的機會。',
    source: '《貓邏輯》危險物品相關內容，依知識庫「環境管理」摘要改寫。',
  ),
  PlanetCard(
    id: '015',
    title: '記下我的日常',
    category: '觀察與紀錄',
    imageAsset: 'assets/cards/015-daily-observation.png',
    petVoice: '多留意我的日常，慢慢更懂我。',
    knowledgePoint: '記錄飲食、排泄與活動，留意和平常不同的變化。',
    source: '《貓邏輯》個別健康觀察相關內容，依知識庫「日常基線」摘要改寫。',
  ),
  PlanetCard(
    id: '016',
    title: '一起學會溫柔',
    category: '孩子與互動',
    imageAsset: 'assets/cards/016-gentle-together.png',
    petVoice: '慢慢陪我就好，讓我自在走動。',
    knowledgePoint: '孩子與貓咪互動時，由成人在旁引導，不追逐或強抱。',
    source: '《貓邏輯》兒童互動相關內容，依知識庫「兒童與來客」摘要改寫。成人需主動監督，並保留貓咪可退回、不被孩子打擾的區域。',
  ),
  PlanetCard(
    id: '017',
    title: '找找小點心',
    category: '尋食與探索',
    imageAsset: 'assets/cards/017-gentle-foraging-v2.png',
    petVoice: '讓我聞一聞，找找藏好的小點心。',
    knowledgePoint: '提供安全、容易上手的尋食活動，依反應調整難度並保留休息。',
    source: '《貓邏輯》遊戲與環境相關內容，依知識庫「安全尋食」摘要改寫。',
  ),
  PlanetCard(
    id: '018',
    title: '轉身也自在',
    category: '貓砂與空間',
    imageAsset: 'assets/cards/018-room-to-turn.png',
    petVoice: '給我寬敞一點，轉身也能自在。',
    knowledgePoint: '選擇大小合適的貓砂盆，讓貓咪能輕鬆轉身。',
    source: '《貓邏輯》貓砂配置相關內容，依知識庫摘要改寫。盆長約鼻端至尾根長度的 1.5 倍，並依個體偏好選擇盆型。',
  ),
  PlanetCard(
    id: '019',
    title: '玩完收起來',
    category: '玩具與收納',
    imageAsset: 'assets/cards/019-store-after-play.png',
    petVoice: '今天先玩到這裡，下次再陪我玩。',
    knowledgePoint: '線繩玩具需有人監督，玩完收妥，避免自行啃咬。',
    source: '《貓邏輯》遊戲與環境相關內容，依知識庫「線繩玩具有人監督，用後收妥」摘要改寫。',
  ),
  PlanetCard(
    id: '020',
    title: '看看我的小肚肚',
    category: '肢體與界線',
    imageAsset: 'assets/cards/020-belly-boundaries.png',
    petVoice: '陪我躺一下，先別急著摸肚肚。',
    knowledgePoint: '翻肚不代表同意摸肚子，尊重貓咪的選擇與界線。',
    source: '《貓邏輯》個體選擇與身體訊號相關內容，依知識庫「翻肚不是摸肚許可」摘要改寫。',
  ),
  PlanetCard(
    id: '021',
    title: '聞聞再前進',
    category: '散步與嗅聞',
    imageAsset: 'assets/cards/021-dog-sniff-walk.png',
    petVoice: '讓我聞一聞，再陪你往前走。',
    knowledgePoint: '散步保留安全嗅聞時間，不急著拉走狗狗。',
    source: '《戴更基教你有效解決狗狗的100個行為問題（2）》 Q65：散步嗅聞，依既有摘要與安全編輯原則改寫。',
  ),
  PlanetCard(
    id: '022',
    title: '鬆鬆一起走',
    category: '牽繩與同行',
    imageAsset: 'assets/cards/022-dog-loose-leash.png',
    petVoice: '繩子鬆鬆的，和你一起慢慢走。',
    knowledgePoint: '獎勵牽繩放鬆時的同行，不用猛拉牽繩。',
    source: '《戴更基教你有效解決狗狗的100個行為問題（1）》 Q39：隨行，依既有摘要與安全編輯原則改寫。',
  ),
  PlanetCard(
    id: '023',
    title: '遠一點也沒關係',
    category: '距離與安心',
    imageAsset: 'assets/cards/023-dog-safe-distance.png',
    petVoice: '離遠一點，我就能慢慢看清楚。',
    knowledgePoint: '遇到刺激先拉開距離，讓狗狗能放鬆再練習。',
    source:
        '《戴更基教你有效解決狗狗的100個行為問題（1）》 Q15、24、29：牽繩與恐懼，依既有摘要與安全編輯原則改寫。出現緊繃、暴衝等反應時先退開，不強迫靠近。',
  ),
  PlanetCard(
    id: '024',
    title: '回來有好事',
    category: '召回與練習',
    imageAsset: 'assets/cards/024-dog-recall.png',
    petVoice: '聽見你叫我，回來有好事。',
    knowledgePoint: '在安全範圍練習召回，回到身邊就給獎勵。',
    source: '《戴更基教你有效解決狗狗的100個行為問題（2）》 Q78：召回，依既有摘要與安全編輯原則改寫。',
  ),
  PlanetCard(
    id: '025',
    title: '小進步也很棒',
    category: '學習與獎勵',
    imageAsset: 'assets/cards/025-dog-small-rewards.png',
    petVoice: '我做到了，請及時鼓勵我。',
    knowledgePoint: '把練習拆成小步驟，及時獎勵自願的動作。',
    source:
        '《戴更基教你有效解決狗狗的100個行為問題（1）》 Q14、37、49／《戴更基教你有效解決狗狗的100個行為問題（2）》 Q71：獎勵與時機，依既有摘要與安全編輯原則改寫。',
  ),
  PlanetCard(
    id: '026',
    title: '讓我自己靠近',
    category: '互動與選擇',
    imageAsset: 'assets/cards/026-dog-voluntary-approach.png',
    petVoice: '給我一點空間，我會自己靠近。',
    knowledgePoint: '讓狗狗自願接近陌生人，不強迫伸手撫摸。',
    source: '《戴更基教你有效解決狗狗的100個行為問題（1）》 Q11、18、19：陌生人與恐懼，依既有摘要與安全編輯原則改寫。',
  ),
  PlanetCard(
    id: '027',
    title: '我的安心小窩',
    category: '空間與休息',
    imageAsset: 'assets/cards/027-dog-safe-den.png',
    petVoice: '想休息的時候，讓我安靜待著。',
    knowledgePoint: '提供能自由進出的安心空間，不追入打擾。',
    source:
        '《戴更基教你有效解決狗狗的100個行為問題（1）》 Q1、7、9：安全空間，依既有摘要與安全編輯原則改寫。安心空間不作懲罰，也不以長時間關籠取代照護。',
  ),
  PlanetCard(
    id: '028',
    title: '雷聲大，我有你',
    category: '聲響與安撫',
    imageAsset: 'assets/cards/028-dog-storm-comfort.png',
    petVoice: '外面好大聲，陪我安心待著。',
    knowledgePoint: '雷雨時提供安靜躲藏處，依狗狗需要陪伴。',
    source:
        '《戴更基教你有效解決狗狗的100個行為問題（1）》 Q8：雷雨恐懼，依既有摘要與安全編輯原則改寫。持續或嚴重恐懼需請獸醫與合格行為專業人員評估。',
  ),
  PlanetCard(
    id: '029',
    title: '門鈴慢慢練習',
    category: '聲音與適應',
    imageAsset: 'assets/cards/029-dog-doorbell-practice.png',
    petVoice: '小小的聲音，我們慢慢練習。',
    knowledgePoint: '從不引起緊張的門鈴聲開始，搭配愉快經驗。',
    source:
        '《戴更基教你有效解決狗狗的100個行為問題（1）》 Q4、25、26：門鈴與聲響，依既有摘要與安全編輯原則改寫。若出現緊張反應，降低音量或暫停，不持續強迫暴露。',
  ),
  PlanetCard(
    id: '030',
    title: '獨處從短短開始',
    category: '獨處與安心',
    imageAsset: 'assets/cards/030-dog-short-alone.png',
    petVoice: '從短短一下開始，陪我慢慢練。',
    knowledgePoint: '從能放鬆的短暫分開開始，依反應調整時間。',
    source:
        '《戴更基教你有效解決狗狗的100個行為問題（1）》 Q42／《戴更基教你有效解決狗狗的100個行為問題（2）》 Q55、58：獨處與分離困擾，依既有摘要與安全編輯原則改寫。依個別反應調整，不讓狗狗持續恐慌硬撐；有分離困擾時尋求專業協助。',
  ),
  PlanetCard(
    id: '031',
    title: '擦腳也能慢慢來',
    category: '合作與照護',
    imageAsset: 'assets/cards/031-dog-cooperative-care.png',
    petVoice: '先讓我準備好，再輕輕擦一下。',
    knowledgePoint: '擦腳練習拆成小步驟，讓狗狗能選擇暫停。',
    source:
        '《戴更基教你有效解決狗狗的100個行為問題（1）》 Q5、47／《戴更基教你有效解決狗狗的100個行為問題（2）》 Q63：合作照護，依既有摘要與安全編輯原則改寫。若出現疼痛或防衛，先停止並評估原因，不強抓固定。',
  ),
  PlanetCard(
    id: '032',
    title: '各自安心吃飯',
    category: '多犬與資源',
    imageAsset: 'assets/cards/032-dog-separate-meals.png',
    petVoice: '有自己的位置，我想安心吃飯。',
    knowledgePoint: '多犬用餐分開安排，避免靠近搶食或打擾。',
    source:
        '《戴更基教你有效解決狗狗的100個行為問題（1）》 Q12、34／《戴更基教你有效解決狗狗的100個行為問題（2）》 Q77、89、100：多犬資源，依既有摘要與安全編輯原則改寫。出現護食或衝突時優先安全管理，不伸手搶碗或安排爭奪。',
  ),
  PlanetCard(
    id: '033',
    title: '用交換，不用搶',
    category: '物品與交換',
    imageAsset: 'assets/cards/033-dog-gentle-trade.png',
    petVoice: '拿喜歡的來換，我們慢慢練習。',
    knowledgePoint: '用合適獎勵練習交換，不追逐或硬搶物品。',
    source:
        '《戴更基教你有效解決狗狗的100個行為問題（2）》 Q52、68、77：拾食與交換，依既有摘要與安全編輯原則改寫。使用安全物品練習；有護物或咬傷風險時由專業人員協助，不徒手強取。',
  ),
  PlanetCard(
    id: '034',
    title: '垃圾桶蓋好',
    category: '收納與安全',
    imageAsset: 'assets/cards/034-dog-secure-storage.png',
    petVoice: '我會好奇，請幫我把危險收好。',
    knowledgePoint: '垃圾與易吞小物妥善收納，減少翻找誤食。',
    source: '《戴更基教你有效解決狗狗的100個行為問題（2）》 Q68、74、75：物品管理，依既有摘要與安全編輯原則改寫。',
  ),
  PlanetCard(
    id: '035',
    title: '咬咬玩具就好',
    category: '遊戲與口腔探索',
    imageAsset: 'assets/cards/035-dog-chew-toy.png',
    petVoice: '想咬咬的時候，給我合適玩具。',
    knowledgePoint: '用安全玩具引導啃咬，不拿手腳陪狗狗玩咬。',
    source:
        '《戴更基教你有效解決狗狗的100個行為問題（2）》 Q54、76、88：遊戲與咬手，依既有摘要與安全編輯原則改寫。依體型與啃咬習慣選擇玩具，監督使用並移除破損物。',
  ),
  PlanetCard(
    id: '036',
    title: '陪孩子學溫柔',
    category: '孩子與安全',
    imageAsset: 'assets/cards/036-dog-child-boundaries.png',
    petVoice: '慢慢陪我就好，讓我自由走動。',
    knowledgePoint: '孩子與狗狗互動由成人監督，不追抱或貼臉。',
    source:
        '《戴更基教你有效解決狗狗的100個行為問題（2）》 Q81、90：兒童與接觸安全，依既有摘要與安全編輯原則改寫。成人須主動監督，保留狗狗可退開且不被打擾的空間。',
  ),
  PlanetCard(
    id: '037',
    title: '上車先熟悉',
    category: '乘車與適應',
    imageAsset: 'assets/cards/037-dog-car-familiarity.png',
    petVoice: '先聞聞、看看，再慢慢上車。',
    knowledgePoint: '從靜止車輛逐步熟悉，上路前妥善固定。',
    source:
        '《戴更基教你有效解決狗狗的100個行為問題（2）》 Q60、91：乘車與旅行，依既有摘要與安全編輯原則改寫。圖示為停車時的適應練習；行車前須用合適設備依產品指示妥善固定。',
  ),
  PlanetCard(
    id: '038',
    title: '找找我的小點心',
    category: '尋食與活動',
    imageAsset: 'assets/cards/038-dog-easy-foraging.png',
    petVoice: '讓我聞一聞，找找小點心。',
    knowledgePoint: '提供安全簡單的尋食活動，依反應調整難度。',
    source:
        '《戴更基教你有效解決狗狗的100個行為問題（2）》 Q97：個別活動與照護空檔，依既有摘要與安全編輯原則改寫。以少量適合的食物練習並計入每日飲食，不使用易吞零件。',
  ),
  PlanetCard(
    id: '039',
    title: '記住如廁時間',
    category: '排泄與日常',
    imageAsset: 'assets/cards/039-dog-toilet-routine.png',
    petVoice: '陪我找對時間，慢慢養成習慣。',
    knowledgePoint: '記錄排泄時機，帶到合適地點並及時獎勵。',
    source:
        '《戴更基教你有效解決狗狗的100個行為問題（1）》 Q17、50：排泄與作息，依既有摘要與安全編輯原則改寫。不限制飲水；突然失禁或排泄改變應先請獸醫評估。',
  ),
  PlanetCard(
    id: '040',
    title: '一步一步慢慢上',
    category: '動線與照護',
    imageAsset: 'assets/cards/040-dog-gentle-steps.png',
    petVoice: '有穩穩的小階梯，我就慢慢上。',
    knowledgePoint: '提供穩固防滑的階梯，配合狗狗的行動能力。',
    source:
        '《戴更基教你有效解決狗狗的100個行為問題（2）》 Q84：樓梯與身體限制，依既有摘要與安全編輯原則改寫。突然抗拒樓梯或出現疼痛時先請獸醫評估，不強迫上下。',
  ),
  PlanetCard(
    id: '041',
    title: '清水隨時有',
    category: '飲水與配置',
    imageAsset: 'assets/cards/041-cat-fresh-water.png',
    petVoice: '想喝水時，總有乾淨的清水。',
    knowledgePoint: '在不同位置提供清水，水碗遠離食物與砂盆。',
    source: 'Cats Protection：Cats and Drinking。 依公開照護資料改寫。',
  ),
  PlanetCard(
    id: '042',
    title: '高處有個好位置',
    category: '垂直與空間',
    imageAsset: 'assets/cards/042-cat-secure-perch.png',
    petVoice: '在穩穩的高處，看看家裡的風景。',
    knowledgePoint: '設置穩固的高處平台，保留安全上下的路線。',
    source:
        'AAFP／ISFM：Feline Environmental Needs Guidelines，垂直空間與安全路線。 依公開照護資料改寫。',
  ),
  PlanetCard(
    id: '043',
    title: '我有喜歡的抓感',
    category: '抓磨與偏好',
    imageAsset: 'assets/cards/043-cat-scratch-choice.png',
    petVoice: '這個抓起來，正合我的心意。',
    knowledgePoint: '提供不同方向與材質的抓面，觀察貓咪偏好。',
    source:
        'Cat Friendly Homes：All You Need to Know About Scratching Posts。 依公開照護資料改寫。',
  ),
  PlanetCard(
    id: '044',
    title: '紙袋先去提把',
    category: '探索與安全',
    imageAsset: 'assets/cards/044-cat-handle-free-bag.png',
    petVoice: '這個紙袋，我想安心探一探。',
    knowledgePoint: '紙袋先移除提把與繩線，再陪貓咪安全探索。',
    source: 'Cats Protection：紙袋移除提把的探索安全建議。 依公開照護資料改寫。',
  ),
  PlanetCard(
    id: '045',
    title: '熟悉的日常節奏',
    category: '作息與安心',
    imageAsset: 'assets/cards/045-cat-steady-routine.png',
    petVoice: '熟悉的日常，讓我慢慢安心。',
    knowledgePoint: '維持可預期的餵食與陪伴，調整作息時循序漸進。',
    source:
        'AAFP／ISFM：Feline Environmental Needs Guidelines，可預期的日常互動。 依公開照護資料改寫。',
  ),
  PlanetCard(
    id: '046',
    title: '留下熟悉的味道',
    category: '氣味與環境',
    imageAsset: 'assets/cards/046-cat-familiar-scent.png',
    petVoice: '熟悉的小毯子，還留著家的味道。',
    knowledgePoint: '寢具分批清洗，保留熟悉氣味，避免濃烈香氛。',
    source:
        'The George Veterinary Group：Creating a Cat-Friendly Home，熟悉氣味與寢具分批清洗。 依公開照護資料改寫。',
  ),
  PlanetCard(
    id: '047',
    title: '廁所位置要安心',
    category: '貓砂與位置',
    imageAsset: 'assets/cards/047-cat-quiet-litter-location.png',
    petVoice: '去小廁所的路，我想自在走。',
    knowledgePoint: '砂盆放在安靜易達處，避開吵雜設備與死角。',
    source: 'Cats Protection：Cats & Toileting，砂盆位置與通行空間。 依公開照護資料改寫。',
  ),
  PlanetCard(
    id: '048',
    title: '新貓砂慢慢選',
    category: '貓砂與偏好',
    imageAsset: 'assets/cards/048-cat-litter-choice.png',
    petVoice: '換個新感覺，也讓我有得選。',
    knowledgePoint: '更換貓砂時保留原有選擇，觀察接受度再調整。',
    source:
        'Cats Protection：Cats & Toileting，依個體偏好保留原有貓砂選擇；圖示為選擇測試，非多貓砂盆的集中配置。 依公開照護資料改寫。',
  ),
  PlanetCard(
    id: '049',
    title: '梳一點，休息一下',
    category: '梳毛與合作',
    imageAsset: 'assets/cards/049-cat-gentle-grooming.png',
    petVoice: '輕輕梳一點，也讓我休息一下。',
    knowledgePoint: '梳毛從短時間開始，出現不適就暫停，不拉扯毛結。',
    source:
        'Cats Protection：Grooming Your Cat。毛結、疼痛或理毛習慣突然改變時請獸醫評估。 依公開照護資料改寫。',
  ),
  PlanetCard(
    id: '050',
    title: '候診也有小屏風',
    category: '就醫與減壓',
    imageAsset: 'assets/cards/050-cat-covered-carrier.png',
    petVoice: '有熟悉的遮擋，我想安靜等一下。',
    knowledgePoint: '候診時可遮蓋外出籠，保持通風並遠離犬隻。',
    source:
        'AAFP：Getting Your Cat to the Veterinary Practice。依貓咪反應調整遮蓋，保持通風；候診時籠門保持關妥。 依公開照護資料改寫。',
  ),
  PlanetCard(
    id: '051',
    title: '新食物慢慢試',
    category: '飲食與轉換',
    imageAsset: 'assets/cards/051-cat-gradual-food.png',
    petVoice: '新的味道，陪我一點一點試。',
    knowledgePoint: '新食物少量提供，逐步轉換，留意食慾與排便。',
    source:
        'Cats Protection：Feeding Your Cat。圖示為新舊食物分碗試吃；若拒食或不適，請聯絡獸醫，不以挨餓迫使接受。 依公開照護資料改寫。',
  ),
  PlanetCard(
    id: '052',
    title: '玩一下，也歇一下',
    category: '遊戲與節奏',
    imageAsset: 'assets/cards/052-cat-short-play.png',
    petVoice: '陪我玩一小段，再一起歇一歇。',
    knowledgePoint: '安排短場次遊戲，依貓咪興趣與體力調整。',
    source: 'Cats Protection：Cats and Play，短場次並依個體調整。 依公開照護資料改寫。',
  ),
  PlanetCard(
    id: '053',
    title: '今天換個玩具',
    category: '玩具與輪替',
    imageAsset: 'assets/cards/053-cat-toy-rotation.png',
    petVoice: '換個新鮮玩法，陪我探索一下。',
    knowledgePoint: '定期輪替安全玩具，檢查破損並更換不安全的玩具。',
    source: 'Cats Protection：Cats and Play，玩具輪替及破損檢查。 依公開照護資料改寫。',
  ),
  PlanetCard(
    id: '054',
    title: '抱抱要有支撐',
    category: '抱持與界線',
    imageAsset: 'assets/cards/054-cat-supported-hold.png',
    petVoice: '托穩我的身體，想下來就放我下來。',
    knowledgePoint: '抱持時支撐胸腹與後軀，不抓頸皮或懸吊四肢。',
    source:
        'Cats Protection：How to Pick Up a Cat。只在貓咪能接受時抱持；想離開就平穩放下。 依公開照護資料改寫。',
  ),
  PlanetCard(
    id: '055',
    title: '呼嚕也要看情境',
    category: '聲音與觀察',
    imageAsset: 'assets/cards/055-cat-purr-context.png',
    petVoice: '聽見我的呼嚕，也看看我的樣子。',
    knowledgePoint: '呼嚕不一定代表開心，要搭配姿勢與當下情境觀察。',
    source:
        'Cats Protection：Cat Body Language。呼嚕也可能出現在壓力或疼痛情境，不能只靠聲音判斷。 依公開照護資料改寫。',
  ),
  PlanetCard(
    id: '056',
    title: '先找原因，別責罵',
    category: '行為與理解',
    imageAsset: 'assets/cards/056-cat-understand-accidents.png',
    petVoice: '先看看我怎麼了，別急著責怪我。',
    knowledgePoint: '異常排泄先找原因，突然改變應就醫，不用責罵處理。',
    source:
        'Cats Protection：Cats & Toileting。突然排泄改變先請獸醫評估；若反覆用力卻無尿，應立即就醫。 依公開照護資料改寫。',
  ),
  PlanetCard(
    id: '057',
    title: '走道留一條路',
    category: '多貓與動線',
    imageAsset: 'assets/cards/057-cat-clear-pathways.png',
    petVoice: '各自有路走，相處就多一點空間。',
    knowledgePoint: '多貓動線保留繞行與退路，避免入口被另一隻貓堵住。',
    source:
        'AAFP：Living with a Clawed Cat，資源通行與避免阻擋。持續追逐或衝突需重新分隔並請專業人員評估。 依公開照護資料改寫。',
  ),
  PlanetCard(
    id: '058',
    title: '低入口更好進',
    category: '高齡與如廁',
    imageAsset: 'assets/cards/058-cat-low-entry-litter.png',
    petVoice: '入口低一點，我就走得更輕鬆。',
    knowledgePoint: '行動不便的貓可用低入口砂盆，放在容易到達的位置。',
    source:
        'Cats Protection：Elderly Cats。配合行動能力改善入口；突然行動改變或疼痛先請獸醫評估。 依公開照護資料改寫。',
  ),
  PlanetCard(
    id: '059',
    title: '清水就很好',
    category: '飲食與常識',
    imageAsset: 'assets/cards/059-cat-water-not-milk.png',
    petVoice: '口渴的時候，清水就很好。',
    knowledgePoint: '牛奶不是貓咪必需品，日常飲水以乾淨清水為主。',
    source: 'Cats Protection：飲食與飲水資料；日常不需餵牛奶。未離乳幼貓的餵養需另依獸醫指示。 依公開照護資料改寫。',
  ),
  PlanetCard(
    id: '060',
    title: '花草先查清楚',
    category: '植物與安全',
    imageAsset: 'assets/cards/060-cat-check-plants.png',
    petVoice: '花草帶回家前，先替我查清楚。',
    knowledgePoint: '百合花、花粉與花瓶水都可能危害貓咪，避免帶入家中。',
    source:
        'FDA：Lovely Lilies and Curious Cats。百合與萱草的花粉、植株及花瓶水可能造成嚴重中毒；疑似接觸立即聯絡獸醫，不等待症狀。 依公開照護資料改寫。',
  ),
  PlanetCard(
    id: '061',
    title: '清水隨時喝',
    category: '飲水與照護',
    imageAsset: 'assets/cards/061-dog-fresh-water.png',
    petVoice: '口渴的時候，總有乾淨的水。',
    knowledgePoint: '隨時提供乾淨飲水，不為了少尿而限制喝水。',
    source: '《戴更基教你有效解決狗狗的100個行為問題（1）》Q3、50，依摘要與 Merck 營養資料改寫；突然飲水量改變請獸醫評估。',
  ),
  PlanetCard(
    id: '062',
    title: '點心也要算進去',
    category: '零食與份量',
    imageAsset: 'assets/cards/062-dog-treat-portions.png',
    petVoice: '小小的點心，也算今天的一份。',
    knowledgePoint: '零食計入每日總熱量，以少量獎勵取代額外加餐。',
    source: 'WSAVA 犬隻零食指引，依公開資料改寫。零食通常不超過每日熱量的 10%；實際份量配合體況、主食及獸醫建議。',
  ),
  PlanetCard(
    id: '063',
    title: '吃飯不用趕',
    category: '進食與節奏',
    imageAsset: 'assets/cards/063-dog-slow-feeding.png',
    petVoice: '有自己的節奏，我想慢慢吃。',
    knowledgePoint: '吃太快可試合適慢食碗，觀察是否挫折或咬碗。',
    source:
        'VCA：How to Keep Puppy from Eating Too Fast，依照護資料改寫。慢食碗依口鼻大小選擇，監督使用；不宣稱可預防胃扭轉或取代醫療。',
  ),
  PlanetCard(
    id: '064',
    title: '胸背帶要合身',
    category: '用品與安全',
    imageAsset: 'assets/cards/064-dog-harness-fit.png',
    petVoice: '穿得合身，走起來才自在。',
    knowledgePoint: '胸背帶依體型調整，檢查磨擦、鬆脫與活動空間。',
    source: 'Dogs Trust：Harness Training，依公開資料改寫。依用品說明與實際體型調整，不以單一固定尺寸適用所有犬隻。',
  ),
  PlanetCard(
    id: '065',
    title: '分開走也很好',
    category: '多犬與散步',
    imageAsset: 'assets/cards/065-dog-separate-walks.png',
    petVoice: '一次陪一隻，也能好好散步。',
    knowledgePoint: '多犬步調不同時可分開散步，配合各自需求。',
    source: '《戴更基教你有效解決狗狗的100個行為問題（1）》Q40：多犬分開散步，依既有摘要改寫。每隻犬都需有合適活動與照護。',
  ),
  PlanetCard(
    id: '066',
    title: '路過也能很自在',
    category: '社交與選擇',
    imageAsset: 'assets/cards/066-dog-no-forced-greeting.png',
    petVoice: '遠遠看見你，也可以各走各的。',
    knowledgePoint: '遇見別犬不必每次打招呼，保留距離與離開的選擇。',
    source: '《戴更基教你有效解決狗狗的100個行為問題（1）》Q19、24，搭配 Dogs Trust 身體語言資料改寫。不強迫近距離社交。',
  ),
  PlanetCard(
    id: '067',
    title: '搖尾也看全身',
    category: '肢體與情境',
    imageAsset: 'assets/cards/067-dog-tail-context.png',
    petVoice: '尾巴動一動，也看看我的全身。',
    knowledgePoint: '搖尾不一定代表友善，要搭配姿勢與情境判斷。',
    source:
        'Dogs Trust：How to Understand Your Dog’s Body Language，依公開資料改寫。不能只以單一尾巴動作判斷情緒或接近安全。',
  ),
  PlanetCard(
    id: '068',
    title: '低吼時先停下',
    category: '警訊與界線',
    imageAsset: 'assets/cards/068-dog-respect-growl.png',
    petVoice: '先停下來，讓我多一點空間。',
    knowledgePoint: '狗狗低吼時先停止逼近，不責罵，再評估原因。',
    source:
        'Dogs Trust：Resource Guarding in Dogs，及既有犬隻摘要改寫。低吼可能有不同情境；停止逼近並確保安全，反覆出現或有咬傷風險請專業協助。',
  ),
  PlanetCard(
    id: '069',
    title: '拉扯也有小規則',
    category: '遊戲與互動',
    imageAsset: 'assets/cards/069-dog-gentle-tug.png',
    petVoice: '輕輕拉、停一下，玩得剛剛好。',
    knowledgePoint: '拉扯遊戲保持低位與短暫休息，不把狗狗吊離地面。',
    source:
        '《戴更基教你有效解決狗狗的100個行為問題（2）》Q88，搭配 Dogs Trust 遊戲資料改寫。選擇適合的完整玩具，停止於過度激動前，不猛甩頭頸。',
  ),
  PlanetCard(
    id: '070',
    title: '睡飽再來玩',
    category: '睡眠與休息',
    imageAsset: 'assets/cards/070-dog-let-sleep.png',
    petVoice: '等我睡飽，再一起慢慢玩。',
    knowledgePoint: '睡覺時避免突然觸碰，讓狗狗自然醒來再互動。',
    source: 'Blue Cross：Do Dogs Dream，依公開資料改寫。一般睡眠不突然搖醒；若疑似急症則需依獸醫指示處理。',
  ),
  PlanetCard(
    id: '071',
    title: '看看獨處的樣子',
    category: '獨處與觀察',
    imageAsset: 'assets/cards/071-dog-alone-video.png',
    petVoice: '你不在身邊時，也留意我的樣子。',
    knowledgePoint: '用影像觀察獨處反應，出現持續焦慮就調整照護。',
    source:
        'Merck：Behavior Problems of Dogs，分離困擾評估與影像觀察，依公開資料改寫。攝影不能取代實際陪伴或照護；持續困擾請獸醫與合格行為專業人員協助。',
  ),
  PlanetCard(
    id: '072',
    title: '客人來先分區',
    category: '來客與管理',
    imageAsset: 'assets/cards/072-dog-visitor-zones.png',
    petVoice: '有自己的區域，我能慢慢適應。',
    knowledgePoint: '來客前安排安全分區，避免狗狗直接衝向門口。',
    source:
        '《戴更基教你有效解決狗狗的100個行為問題（2）》Q62、92，搭配 Dogs Trust 資源管理資料改寫。隔欄須合乎體型且固定可靠；如隔欄使狗更焦慮，改用能安心休息的獨立空間。',
  ),
  PlanetCard(
    id: '073',
    title: '小動物分開保護',
    category: '共處與安全',
    imageAsset: 'assets/cards/073-dog-protect-small-pets.png',
    petVoice: '各自有空間，才能安心生活。',
    knowledgePoint: '有追逐風險時分隔小動物，不放任狗狗追趕練習。',
    source:
        '《戴更基教你有效解決狗狗的100個行為問題（2）》Q80，搭配 Merck 犬隻行為管理資料改寫。捕獵追逐需可靠物理分隔，不以放開測試是否友善。',
  ),
  PlanetCard(
    id: '074',
    title: '腳下穩穩的',
    category: '地面與行動',
    imageAsset: 'assets/cards/074-dog-nonslip-path.png',
    petVoice: '腳下不打滑，我就走得更安心。',
    knowledgePoint: '在常走動線鋪穩固防滑墊，避免滑動與翹起的邊角。',
    source: 'The Rehab Vet：犬隻居家環境與防滑建議，依資料改寫。防滑改善不能取代疼痛或行動障礙的獸醫評估。',
  ),
  PlanetCard(
    id: '075',
    title: '先認識小梳子',
    category: '梳理與適應',
    imageAsset: 'assets/cards/075-dog-brush-familiarity.png',
    petVoice: '先聞聞小梳子，再輕輕梳一下。',
    knowledgePoint: '先讓狗狗熟悉梳具，短時間輕梳，避免硬扯毛結。',
    source:
        '《戴更基教你有效解決狗狗的100個行為問題（1）》合作照護原則，搭配 RSPCA 梳理資料改寫。依毛況選擇梳具，疼痛或嚴重毛結交由獸醫或合格美容人員處理。',
  ),
  PlanetCard(
    id: '076',
    title: '刷牙慢慢練',
    category: '口腔與照護',
    imageAsset: 'assets/cards/076-dog-toothbrush-practice.png',
    petVoice: '先熟悉小牙刷，再慢慢練習。',
    knowledgePoint: '刷牙循序適應，使用犬用牙膏，不用人用牙膏。',
    source:
        'VCA：How to Brush Your Pet’s Teeth，依公開資料改寫。先請獸醫確認口腔狀況與示範；疼痛、出血或抗拒加劇時停止並就醫。',
  ),
  PlanetCard(
    id: '077',
    title: '洗澡腳下要穩',
    category: '洗澡與照護',
    imageAsset: 'assets/cards/077-dog-bath-nonslip.png',
    petVoice: '腳下穩穩的，我們慢慢洗。',
    knowledgePoint: '洗澡先鋪防滑墊，水流避開眼耳，依反應暫停。',
    source:
        '《戴更基教你有效解決狗狗的100個行為問題（1）》Q5、6，依合作照護摘要與 RSPCA 用品安全原則改寫。水溫舒適、避免水流沖入眼耳，不強迫驚恐犬；用品依獸醫建議與標示。',
  ),
  PlanetCard(
    id: '078',
    title: '便便記得清',
    category: '散步與衛生',
    imageAsset: 'assets/cards/078-dog-poop-cleanup.png',
    petVoice: '散步留下回憶，便便記得帶走。',
    knowledgePoint: '外出即時清理狗狗糞便，處理後記得洗手。',
    source:
        'CDC：Dogs／Healthy Pets, Healthy People，依公開衛生資料改寫。即使使用袋子處理，接觸糞便後仍需清潔雙手。',
  ),
  PlanetCard(
    id: '079',
    title: '地上的先繞開',
    category: '外出與拾食',
    imageAsset: 'assets/cards/079-dog-avoid-street-food.png',
    petVoice: '地上有東西，陪我一起繞開。',
    knowledgePoint: '散步留意地面食物，提早繞開，不讓狗狗反覆撿食。',
    source:
        '《戴更基教你有效解決狗狗的100個行為問題（2）》Q52、66、99，依既有摘要改寫。疑似吞入有毒物或異物即聯絡獸醫，不徒手硬搶或自行催吐。',
  ),
  PlanetCard(
    id: '080',
    title: '有個地方可以挖',
    category: '挖掘與活動',
    imageAsset: 'assets/cards/080-dog-digging-zone.png',
    petVoice: '這裡可以挖，陪我探索一下。',
    knowledgePoint: '安排安全的挖掘區，使用合適材料並在旁監督。',
    source:
        'Dogs Trust：How to Make Your Garden Dog Friendly，依公開照護資料改寫。挖掘區避開肥料、尖銳物與電線；若吞吃填材即停止並調整。',
  ),
  PlanetCard(
    id: '081',
    title: '慢慢眨眼就好',
    category: '眼神與互動',
    imageAsset: 'assets/cards/081-cat-slow-blink.png',
    petVoice: '慢慢眨眨眼，我們輕鬆打招呼。',
    knowledgePoint: '可用慢眨眼回應貓咪，避免長時間直盯雙眼。',
    source:
        'Cats Protection：Feline Behaviour Visual Guides，慢眨眼段落，依公開資料改寫。眼神應搭配全身姿勢與當下情境，不保證每隻貓都回應。',
  ),
  PlanetCard(
    id: '082',
    title: '踩踩柔軟的小毯子',
    category: '踩奶與行為',
    imageAsset: 'assets/cards/082-cat-kneading-blanket.png',
    petVoice: '軟軟的小毯子，讓我踩踩就好。',
    knowledgePoint: '踩奶延續幼貓時期的動作，可提供柔軟毯子承接。',
    source: '《貓邏輯》Q22 與 Cats Protection 踩奶資料改寫。踩奶不直接等同確定心念；被爪子碰痛可用毯子隔開，不責罵。',
  ),
  PlanetCard(
    id: '083',
    title: '蹭蹭留下熟悉味',
    category: '氣味與溝通',
    imageAsset: 'assets/cards/083-cat-cheek-rub.png',
    petVoice: '輕輕蹭一蹭，留下熟悉的味道。',
    knowledgePoint: '臉頰磨蹭會留下氣味標記，是貓咪常見的溝通方式。',
    source:
        'Cats Protection：Feline Behaviour Visual Guides，磨蹭與氣味段落，依公開資料改寫。不將單一磨蹭動作翻譯為固定心念。',
  ),
  PlanetCard(
    id: '084',
    title: '鬍鬚是我的小幫手',
    category: '感官與照護',
    imageAsset: 'assets/cards/084-cat-protect-whiskers.png',
    petVoice: '長長的小鬍鬚，陪我認識世界。',
    knowledgePoint: '鬍鬚協助感知周遭，不修剪、拔除或拉扯鬍鬚。',
    source:
        'Cats Protection：Why Do Cats Have Whiskers，依公開資料改寫。鬍鬚是感覺工具；自然脫落與刻意剪拔不同，不宣稱掉鬍鬚必然失去平衡。',
  ),
  PlanetCard(
    id: '085',
    title: '晨昏想動一動',
    category: '活動與時段',
    imageAsset: 'assets/cards/085-cat-dawn-dusk-play.png',
    petVoice: '天剛亮或將暗，我想動一動。',
    knowledgePoint: '貓咪常在清晨與黃昏較活躍，可安排合適的互動活動。',
    source:
        'Cats Protection：Cats at Night，依公開資料改寫。晨昏活躍是常見節律，個體作息不同；突然夜叫或活動改變仍需留意身體原因。',
  ),
  PlanetCard(
    id: '086',
    title: '貓薄荷反應不一樣',
    category: '嗅覺與偏好',
    imageAsset: 'assets/cards/086-cat-catnip-response.png',
    petVoice: '有沒有喜歡，每隻貓都不一樣。',
    knowledgePoint: '貓薄荷反應因貓而異，沒反應也正常，不必強迫使用。',
    source:
        '《貓邏輯》Q30 與 Cats Protection：Cats and Catnip 改寫。此處指貓薄荷，不是貓草；以完整貓用填充玩具少量接觸，不灌食或使用精油。',
  ),
  PlanetCard(
    id: '087',
    title: '砂盆多備一個',
    category: '多貓與資源',
    imageAsset: 'assets/cards/087-cat-extra-litter-tray.png',
    petVoice: '多一個選擇，上廁所更從容。',
    knowledgePoint: '砂盆以貓數加一為起點，分布在不同位置而非並排。',
    source: 'Cats Protection：Cats & Toileting，依公開資料改寫。數量只是起點，仍需配合樓層、通行與貓咪關係調整。',
  ),
  PlanetCard(
    id: '088',
    title: '有蓋無蓋讓我選',
    category: '砂盆與形式',
    imageAsset: 'assets/cards/088-cat-litter-cover-choice.png',
    petVoice: '有蓋或沒蓋，讓我試試喜歡哪個。',
    knowledgePoint: '有蓋或開放式砂盆各有偏好，可提供選擇並觀察使用。',
    source:
        'Cats Protection：Cats & Toileting，依公開資料改寫。比較時保留既有可用砂盆；有蓋盆入口不加擺動門片，內部需寬敞。',
  ),
  PlanetCard(
    id: '089',
    title: '貓砂不用香香',
    category: '貓砂與氣味',
    imageAsset: 'assets/cards/089-cat-unscented-litter.png',
    petVoice: '自然的味道，讓我安心上廁所。',
    knowledgePoint: '貓砂優先選無香味款，不用香粉掩蓋髒污。',
    source:
        'Cat Friendly Homes：Everything You Should Know About Litter Boxes，與《貓邏輯》砂盆照護摘要改寫。無香味不能取代清潔；材料仍依個體接受度選擇。',
  ),
  PlanetCard(
    id: '090',
    title: '項圈要能快解',
    category: '配件與安全',
    imageAsset: 'assets/cards/090-cat-breakaway-collar.png',
    petVoice: '小小的項圈，也要留意安全。',
    knowledgePoint: '若佩戴項圈，選可快解款並定期檢查鬆緊與磨擦。',
    source:
        'Cats Protection：Caring for Your Cat 2025，項圈段落，依公開資料改寫。項圈不是每隻貓必需；依實際體型與產品說明適配，不能代替晶片資料。',
  ),
  PlanetCard(
    id: '091',
    title: '晶片資料記得更新',
    category: '識別與聯絡',
    imageAsset: 'assets/cards/091-cat-microchip-details.png',
    petVoice: '聯絡資料對，找到我才聯絡得到你。',
    knowledgePoint: '晶片登記的電話與地址有變更時，記得更新聯絡資料。',
    source:
        'Cats Protection：Caring for Your Cat 2025，晶片資料維護段落，依公開資料改寫。不套用英國法規為台灣規定；晶片不是 GPS。',
  ),
  PlanetCard(
    id: '092',
    title: '搬家先安頓一室',
    category: '搬家與適應',
    imageAsset: 'assets/cards/092-cat-moving-safe-room.png',
    petVoice: '先有熟悉的一室，再慢慢認識新家。',
    knowledgePoint: '搬家先安頓在備妥用品的房間，再依反應擴大探索。',
    source:
        'Cats Protection：Moving House With a Cat，依公開資料改寫。先確認門窗防逃與用品分區，逐步探索，避免固定天數保證適應。',
  ),
  PlanetCard(
    id: '093',
    title: '上車先固定好',
    category: '乘車與安全',
    imageAsset: 'assets/cards/093-cat-secure-travel-carrier.png',
    petVoice: '穩穩待在籠裡，陪我平安到達。',
    knowledgePoint: '乘車時關妥並固定外出籠，不讓貓咪在車內自由走動。',
    source:
        'Cats Protection：Travelling With Your Cat，依公開資料改寫。固定方式依外出籠與車輛說明；保持通風，不把貓單獨留在車內。',
  ),
  PlanetCard(
    id: '094',
    title: '胖瘦不只看毛',
    category: '體態與觀察',
    imageAsset: 'assets/cards/094-cat-body-condition.png',
    petVoice: '毛茸茸的外表，也要仔細看看。',
    knowledgePoint: '評估體態要看腰身並觸摸肋骨，長毛不能只靠外觀。',
    source:
        'WSAVA：Cat Body Condition Scoring 2017，依公開資料改寫。由獸醫示範體態評估，不能只看體重或毛量；不自行極端節食。',
  ),
  PlanetCard(
    id: '095',
    title: '份量先秤好',
    category: '飲食與份量',
    imageAsset: 'assets/cards/095-cat-weighed-portions.png',
    petVoice: '今天吃多少，先幫我量剛好。',
    knowledgePoint: '用電子秤量好主食份量，再依體況與獸醫建議調整。',
    source:
        'VCA：Nutrition — General Feeding Guidelines for Cats，依公開資料改寫。主食份量依熱量與個體需求決定，秤重不能取代營養評估，不突然禁食。',
  ),
  PlanetCard(
    id: '096',
    title: '玩具要抓得到',
    category: '遊戲與滿足',
    imageAsset: 'assets/cards/096-cat-catchable-toy.png',
    petVoice: '追一追，也讓我真的抓得到。',
    knowledgePoint: '用能抓住的實體玩具，避免只有追不到的光點。',
    source:
        'Cats Protection：Behaviour Guide，環境豐富化與雷射玩具段落，依公開資料改寫。玩耍需讓貓能捕捉實物，依興趣結束；不把雷射照向眼睛。',
  ),
  PlanetCard(
    id: '097',
    title: '牙齒照護慢慢來',
    category: '口腔與練習',
    imageAsset: 'assets/cards/097-cat-toothbrush-introduction.png',
    petVoice: '先聞聞小牙刷，慢慢熟悉就好。',
    knowledgePoint: '刷牙先循序適應，使用貓用牙膏，不用人用牙膏。',
    source:
        'VCA：How to Brush Your Pet’s Teeth，貓犬通用照護部分，依公開資料改寫。先請獸醫確認口腔狀況並示範；疼痛或明顯抗拒先停止，不硬掰嘴。',
  ),
  PlanetCard(
    id: '098',
    title: '剪指甲先練習',
    category: '指甲與合作',
    imageAsset: 'assets/cards/098-cat-nail-care-practice.png',
    petVoice: '先輕輕碰碰腳，一點一點練習。',
    knowledgePoint: '剪指甲先適應碰腳，不確定剪哪裡就請專業示範。',
    source:
        'Cats Protection：Grooming Your Cat，修剪指甲與低限制照護段落，依公開資料改寫。依指甲狀況判斷是否需修剪，避開血管；不以圖卡取代實際示範。',
  ),
  PlanetCard(
    id: '099',
    title: '舔不停先找原因',
    category: '理毛與健康',
    imageAsset: 'assets/cards/099-cat-overgrooming-check.png',
    petVoice: '舔個不停時，陪我找找原因。',
    knowledgePoint: '過度理毛或出現禿毛，先請獸醫排除身體問題。',
    source:
        '《貓邏輯》Q11 與 Cornell：Cats That Lick Too Much，依公開資料改寫。先排除疼痛、皮膚等身體因素，不直接歸因壓力或責罵。',
  ),
  PlanetCard(
    id: '100',
    title: '啟動前先找找我',
    category: '家電與安全',
    imageAsset: 'assets/cards/100-cat-check-appliances.png',
    petVoice: '按下啟動前，先確認我在哪裡。',
    knowledgePoint: '洗衣機、烘衣機啟動前先檢查滾筒，平時關好機門。',
    source:
        'Cats Protection：Keeping Your Cat Safe in the Home，依公開資料改寫。開門裝卸時持續看顧，確認貓在安全處再關門啟動，避免困在家電內。',
  ),
  PlanetCard(
    id: '101',
    title: '墊子上放鬆',
    category: '安定與練習',
    imageAsset: 'assets/cards/101-dog-mat-settle.png',
    petVoice: '待在小墊子上，也能很自在。',
    knowledgePoint: '在墊子上安定放鬆時給獎勵，慢慢延長時間。',
    source:
        'Dogs Trust 犬隻訓練：墊子上放鬆，依公開資料改寫。 https://www.dogstrust.org.uk/dog-advice/training/basics/settle-training',
  ),
  PlanetCard(
    id: '102',
    title: '四隻腳穩穩站',
    category: '迎接與禮貌',
    imageAsset: 'assets/cards/102-dog-four-paws.png',
    petVoice: '腳腳留在地上，也能等到你。',
    knowledgePoint: '迎接時獎勵四腳著地，不推撞或用膝蓋頂狗狗。',
    source:
        'Dogs Trust 犬隻訓練：四隻腳穩穩站，依公開資料改寫。 https://www.dogstrust.org.uk/dog-advice/training/unwanted-behaviours/jumping-up-training',
  ),
  PlanetCard(
    id: '103',
    title: '鼻子輕輕碰',
    category: '互動與練習',
    imageAsset: 'assets/cards/103-dog-nose-target.png',
    petVoice: '輕輕碰一下，我懂你的邀請。',
    knowledgePoint: '鼻碰手練習由狗狗主動觸碰，不把手壓向鼻子。',
    source:
        'Dogs Trust 犬隻訓練：鼻子輕輕碰，依公開資料改寫。 https://www.dogstrust.org.uk/dog-advice/training/tips-tricks/target-training',
  ),
  PlanetCard(
    id: '104',
    title: '名字是好消息',
    category: '注意與連結',
    imageAsset: 'assets/cards/104-dog-name-attention.png',
    petVoice: '聽見我的名字，我想看看你。',
    knowledgePoint: '叫名字後狗狗轉頭看你就獎勵，避免連續喊叫。',
    source:
        'Dogs Trust 犬隻訓練：名字是好消息，依公開資料改寫。 https://www.dogstrust.org.uk/dog-advice/training/basics/name-training',
  ),
  PlanetCard(
    id: '105',
    title: '等一下再出發',
    category: '等待與口令',
    imageAsset: 'assets/cards/105-dog-stay-release.png',
    petVoice: '短短等一下，再一起行動。',
    knowledgePoint: '等待練習從短時間開始，用解除口令結束。',
    source:
        'Dogs Trust 犬隻訓練：等一下再出發，依公開資料改寫。 https://www.dogstrust.org.uk/dog-advice/training/basics/stay-training',
  ),
  PlanetCard(
    id: '106',
    title: '練一下，休息一下',
    category: '學習與節奏',
    imageAsset: 'assets/cards/106-dog-short-sessions.png',
    petVoice: '短短練習，留點期待給下次。',
    knowledgePoint: '訓練採短場次，疲累或分心時先休息。',
    source:
        'RSPCA 犬隻照護與訓練：練一下，休息一下，依公開資料改寫。 https://www.rspca.org.uk/adviceandwelfare/pets/dogs/training',
  ),
  PlanetCard(
    id: '107',
    title: '家人說法要一致',
    category: '口令與溝通',
    imageAsset: 'assets/cards/107-dog-consistent-cues.png',
    petVoice: '同一個意思，我就更容易懂。',
    knowledgePoint: '家人使用一致口令與手勢，避免同時下指令。',
    source:
        'Dogs Trust 犬隻訓練：家人說法要一致，依公開資料改寫。 https://www.dogstrust.org.uk/dog-advice/training/techniques/top-ten-dog-training-tips',
  ),
  PlanetCard(
    id: '108',
    title: '安靜一點更好學',
    category: '環境與專注',
    imageAsset: 'assets/cards/108-dog-quiet-learning.png',
    petVoice: '少一點干擾，我能慢慢學。',
    knowledgePoint: '新動作先在安靜少干擾的室內練習。',
    source:
        'RSPCA 犬隻照護與訓練：安靜一點更好學，依公開資料改寫。 https://www.rspca.org.uk/adviceandwelfare/pets/dogs/training',
  ),
  PlanetCard(
    id: '109',
    title: '換地方再練習',
    category: '學習與情境',
    imageAsset: 'assets/cards/109-dog-new-place.png',
    petVoice: '換個地方，陪我重新熟悉。',
    knowledgePoint: '換到新地點練習時降低難度，再逐漸增加干擾。',
    source:
        'Dogs Trust 犬隻訓練：換地方再練習，依公開資料改寫。 https://www.dogstrust.org.uk/dog-advice/training/techniques/top-ten-dog-training-tips',
  ),
  PlanetCard(
    id: '110',
    title: '喜歡的才是獎勵',
    category: '獎勵與偏好',
    imageAsset: 'assets/cards/110-dog-reward-choice.png',
    petVoice: '你知道我喜歡什麼，真好。',
    knowledgePoint: '依狗狗偏好選擇食物、玩具或稱讚作為獎勵。',
    source:
        'RSPCA 犬隻照護與訓練：喜歡的才是獎勵，依公開資料改寫。 https://www.rspca.org.uk/adviceandwelfare/pets/dogs/training',
  ),
  PlanetCard(
    id: '111',
    title: '玩具洗好再玩',
    category: '玩具與清潔',
    imageAsset: 'assets/cards/111-dog-clean-toys.png',
    petVoice: '乾乾淨淨，再陪我玩一次。',
    knowledgePoint: '玩具依材質清潔，充分沖洗並乾燥後再給狗狗。',
    source:
        'RSPCA 犬隻照護與訓練：玩具洗好再玩，依公開資料改寫。 https://www.rspca.org.uk/adviceandwelfare/pets/dogs/environment',
  ),
  PlanetCard(
    id: '112',
    title: '每隻都有舒服床',
    category: '多犬與休息',
    imageAsset: 'assets/cards/112-dog-enough-beds.png',
    petVoice: '有自己的床，休息更自在。',
    knowledgePoint: '多犬家庭提供足夠床位，避免爭搶休息位置。',
    source:
        'RSPCA 犬隻照護與訓練：每隻都有舒服床，依公開資料改寫。 https://www.rspca.org.uk/adviceandwelfare/pets/dogs/environment',
  ),
  PlanetCard(
    id: '113',
    title: '圍欄先檢查',
    category: '戶外與防逃',
    imageAsset: 'assets/cards/113-dog-secure-yard.png',
    petVoice: '圍好小院子，探索更安心。',
    knowledgePoint: '庭院活動前檢查圍欄與大門，避免縫隙逃脫。',
    source:
        'Dogs Trust 犬隻訓練：圍欄先檢查，依公開資料改寫。 https://www.dogstrust.org.uk/dog-advice/training/unwanted-behaviours/escaping-and-running-away',
  ),
  PlanetCard(
    id: '114',
    title: '步調跟著我',
    category: '活動與體力',
    imageAsset: 'assets/cards/114-dog-exercise-fit.png',
    petVoice: '今天走多少，看看我的狀態。',
    knowledgePoint: '運動量依年齡、健康與體力調整，不一味加量。',
    source:
        'RSPCA 犬隻照護與訓練：步調跟著我，依公開資料改寫。 https://www.rspca.org.uk/adviceandwelfare/pets/dogs',
  ),
  PlanetCard(
    id: '115',
    title: '日常有個節奏',
    category: '作息與安心',
    imageAsset: 'assets/cards/115-dog-daily-routine.png',
    petVoice: '熟悉的日常，讓我好安心。',
    knowledgePoint: '建立可預期的日常作息，保留吃飯、活動與休息時間。',
    source:
        'Dogs Trust 犬隻訓練：日常有個節奏，依公開資料改寫。 https://www.dogstrust.org.uk/dog-advice/training/home/create-routine',
  ),
  PlanetCard(
    id: '116',
    title: '門口先停一下',
    category: '出入與安全',
    imageAsset: 'assets/cards/116-dog-doorway-pause.png',
    petVoice: '等門開好了，我們再一起走。',
    knowledgePoint: '出門前先繫妥牽繩，在門口練習停等再通行。',
    source:
        'Dogs Trust 犬隻訓練：門口先停一下，依公開資料改寫。 https://www.dogstrust.org.uk/dog-advice/training/home/doorway-training',
  ),
  PlanetCard(
    id: '117',
    title: '先認識吸塵器',
    category: '聲音與適應',
    imageAsset: 'assets/cards/117-dog-vacuum-intro.png',
    petVoice: '先遠遠看看，不急著靠近。',
    knowledgePoint: '先從關機的吸塵器開始熟悉，不追著狗狗吸。',
    source:
        'Dogs Trust 犬隻訓練：先認識吸塵器，依公開資料改寫。 https://www.dogstrust.org.uk/dog-advice/training/home/vacuum-cleaner',
  ),
  PlanetCard(
    id: '118',
    title: '做對了，告訴我',
    category: '標記與學習',
    imageAsset: 'assets/cards/118-dog-marker-word.png',
    petVoice: '這聲鼓勵，讓我知道做對了。',
    knowledgePoint: '用固定標記詞指出做對的瞬間，接著給獎勵。',
    source:
        'Dogs Trust 犬隻訓練：做對了，告訴我，依公開資料改寫。 https://www.dogstrust.org.uk/dog-advice/training/techniques/introducing-a-marker',
  ),
  PlanetCard(
    id: '119',
    title: '嘴套也能慢慢學',
    category: '用品與適應',
    imageAsset: 'assets/cards/119-dog-muzzle-choice.png',
    petVoice: '讓我自己試試，也能隨時退開。',
    knowledgePoint: '嘴套練習讓狗狗自願探入，初期不扣住或強戴。',
    source:
        'Dogs Trust 犬隻訓練：嘴套也能慢慢學，依公開資料改寫。 https://www.dogstrust.org.uk/dog-advice/training/outdoors/muzzle-training',
  ),
  PlanetCard(
    id: '120',
    title: '玩具回小籃子',
    category: '遊戲與學習',
    imageAsset: 'assets/cards/120-dog-tidy-toys.png',
    petVoice: '玩完放回去，也是一個遊戲。',
    knowledgePoint: '收玩具練習從籃子旁開始，放入就給獎勵。',
    source:
        'Dogs Trust 犬隻訓練：玩具回小籃子，依公開資料改寫。 https://www.dogstrust.org.uk/dog-advice/training/tips-tricks/tidying-up',
  ),
  PlanetCard(
    id: '121',
    title: '鼻子輕碰一下',
    category: '互動與學習',
    imageAsset: 'assets/cards/121-cat-nose-target.png',
    petVoice: '輕輕碰一下，就有小驚喜。',
    knowledgePoint: '用鼻子觸碰目標物就給獎勵，不把目標物戳向貓咪。',
    source:
        'Happy Cats Haven：Clicker Training Behaviors for Cats，依公開資料改寫。 https://happycatshaven.org/resource/clicker-training-behaviors-cats/',
  ),
  PlanetCard(
    id: '122',
    title: '名字裡有好事',
    category: '注意與連結',
    imageAsset: 'assets/cards/122-cat-name-reward.png',
    petVoice: '聽見我的名字，我想看看你。',
    knowledgePoint: '叫名字後貓咪看向你就給獎勵，不用提高音量催促。',
    source:
        'Cats Protection：名字回應與獎勵練習，依公開資料改寫。 https://www.cats.org.uk/cats-blog/how-to-train-your-cat-respond-to-name',
  ),
  PlanetCard(
    id: '123',
    title: '小墊子集合',
    category: '學習與位置',
    imageAsset: 'assets/cards/123-cat-mat-training.png',
    petVoice: '走到小墊子上，也有小驚喜。',
    knowledgePoint: '墊上練習從踩到墊面開始，再逐步增加停留時間。',
    source:
        'Happy Cats Haven：Clicker Training Behaviors for Cats，依公開資料改寫。 https://happycatshaven.org/resource/clicker-training-behaviors-cats/',
  ),
  PlanetCard(
    id: '124',
    title: '懂我喜歡的獎勵',
    category: '學習與偏好',
    imageAsset: 'assets/cards/124-cat-reward-preference.png',
    petVoice: '我喜歡的，你都記在心裡。',
    knowledgePoint: '依貓咪偏好選獎勵，不把每隻貓都當成愛吃點心。',
    source:
        'Cats Protection：名字回應與獎勵練習，依公開資料改寫。 https://www.cats.org.uk/cats-blog/how-to-train-your-cat-respond-to-name',
  ),
  PlanetCard(
    id: '125',
    title: '外出籠抱穩穩',
    category: '外出與照護',
    imageAsset: 'assets/cards/125-cat-carrier-support.png',
    petVoice: '穩穩托住，我比較安心。',
    knowledgePoint: '搬運外出籠時托住底部，保持水平並減少晃動。',
    source:
        'Battersea：Travelling with cats，依公開資料改寫。 https://www.battersea.org.uk/pet-advice/cat-advice/travelling-cats',
  ),
  PlanetCard(
    id: '126',
    title: '看診回家緩一緩',
    category: '多貓與照護',
    imageAsset: 'assets/cards/126-cat-home-from-vet.png',
    petVoice: '回到家，給我一點緩衝時間。',
    knowledgePoint: '看診返家的貓若引起同伴緊張，先分室休息再重聚。',
    source:
        'Cats Protection：Getting Another Cat，依公開資料改寫。 https://www.cats.org.uk/help-and-advice/cats-and-your-family/other-cats',
  ),
  PlanetCard(
    id: '127',
    title: '摸一下，先停手',
    category: '撫摸與界線',
    imageAsset: 'assets/cards/127-cat-petting-pause.png',
    petVoice: '停一下，看看我還想不想。',
    knowledgePoint: '撫摸幾下就停手，觀察貓咪是否還想互動。',
    source:
        'International Cat Care：Cat Friendly Homing Information Pack，三秒撫摸原則，依公開資料改寫。 https://icatcare.org/resources/cat_friendly_homing_information_pack.pdf',
  ),
  PlanetCard(
    id: '128',
    title: '嘶聲是在說暫停',
    category: '訊號與距離',
    imageAsset: 'assets/cards/128-cat-hiss-space.png',
    petVoice: '我需要空間，請先退一點。',
    knowledgePoint: '貓咪發出嘶聲時先退開，不模仿嘶聲或責罵。',
    source:
        'Cats Protection：Cat Body Language，依公開資料改寫。 https://www.cats.org.uk/help-and-advice/cat-behaviour/cat-body-language',
  ),
  PlanetCard(
    id: '129',
    title: '瞳孔也看光線',
    category: '觀察與情境',
    imageAsset: 'assets/cards/129-cat-pupils-light.png',
    petVoice: '看看光線，再看看我的樣子。',
    knowledgePoint: '瞳孔大小也受光線影響，不能只憑瞳孔判斷情緒。',
    source:
        'Cats Protection：Cat eyesight facts；情緒判讀另參考 Cat Body Language，依公開資料改寫。 https://www.cats.org.uk/cats-blog/cat-eyesight-facts',
  ),
  PlanetCard(
    id: '130',
    title: '豎起尾巴打招呼',
    category: '訊號與交流',
    imageAsset: 'assets/cards/130-cat-tail-greeting.png',
    petVoice: '尾巴豎起來，跟你說聲嗨。',
    knowledgePoint: '豎尾配合放鬆姿勢常是友善訊號，仍要看整體情境。',
    source:
        'Cats Protection：Cat Body Language，依公開資料改寫。 https://www.cats.org.uk/help-and-advice/cat-behaviour/cat-body-language',
  ),
  PlanetCard(
    id: '131',
    title: '追逐也要看反應',
    category: '多貓與遊戲',
    imageAsset: 'assets/cards/131-cat-play-boundaries.png',
    petVoice: '玩得舒服，我們才繼續。',
    knowledgePoint: '追逐若總是一方逃躲，應中止互動並評估壓力。',
    source:
        'Cats Protection：Cats and Fighting，依公開資料改寫。 https://www.cats.org.uk/help-and-advice/cat-behaviour/cats-and-fighting',
  ),
  PlanetCard(
    id: '132',
    title: '抓板放對地方',
    category: '抓磨與配置',
    imageAsset: 'assets/cards/132-cat-scratch-location.png',
    petVoice: '想抓抓時，旁邊就找得到。',
    knowledgePoint: '抓板可放在常抓的家具旁，提供就近替代位置。',
    source:
        'Cats Protection：Behaviour focus: Scratching，依公開資料改寫。 https://www.cats.org.uk/cats-blog/behaviour-focus-scratching',
  ),
  PlanetCard(
    id: '133',
    title: '碗洗好再開飯',
    category: '餐具與清潔',
    imageAsset: 'assets/cards/133-cat-clean-bowl.png',
    petVoice: '乾淨的小碗，吃飯更舒服。',
    knowledgePoint: '食碗用後清洗並充分沖淨，避免殘留舊食與清潔劑。',
    source:
        'Cats Protection：貓咪照護手冊，餐後清洗食碗，依公開資料改寫。 https://www.cats.org.uk/uploads/documents/Cats_Protection_JCC_Leaflet.pdf',
  ),
  PlanetCard(
    id: '134',
    title: '流水也能試試看',
    category: '飲水與選擇',
    imageAsset: 'assets/cards/134-cat-flowing-water.png',
    petVoice: '有流動的水，我想試著喝。',
    knowledgePoint: '可提供寵物飲水機，觀察貓咪是否偏好流動的水。',
    source:
        'Cats Protection：Why do cats love running water?，依公開資料改寫。 https://www.cats.org.uk/cats-blog/why-cats-love-running-water',
  ),
  PlanetCard(
    id: '135',
    title: '寬口小碗試試看',
    category: '餐具與選擇',
    imageAsset: 'assets/cards/135-cat-wide-bowl.png',
    petVoice: '換個寬口小碗，試試喜不喜歡。',
    knowledgePoint: '可試寬口淺碗，依貓咪實際使用情形調整。',
    source:
        'Cats Protection：Water, domestic cat，依公開資料改寫。 https://learnonline.cats.org.uk/content/ufo/23.html',
  ),
  PlanetCard(
    id: '136',
    title: '各有舒服的小床',
    category: '多貓與資源',
    imageAsset: 'assets/cards/136-cat-extra-beds.png',
    petVoice: '想休息時，都有自己的位置。',
    knowledgePoint: '多貓家庭提供足夠床位，讓貓咪能分散休息。',
    source:
        'Cats Protection：Getting Another Cat，依公開資料改寫。 https://www.cats.org.uk/help-and-advice/cats-and-your-family/other-cats',
  ),
  PlanetCard(
    id: '137',
    title: '帶上熟悉的小毯',
    category: '外出與安心',
    imageAsset: 'assets/cards/137-cat-familiar-blanket.png',
    petVoice: '熟悉的小毯，也陪我出門。',
    knowledgePoint: '外出時帶上有熟悉氣味的小毯，減少環境陌生感。',
    source:
        'Cats Protection：Choosing and Using a Cat Carrier，依公開資料改寫。 https://www.cats.org.uk/help-and-advice/getting-a-cat/how-to-choose-and-use-a-cat-carrier',
  ),
  PlanetCard(
    id: '138',
    title: '窗簾拉繩收好',
    category: '居家與安全',
    imageAsset: 'assets/cards/138-cat-blind-cords.png',
    petVoice: '窗邊看風景，拉繩先收好。',
    knowledgePoint: '窗簾拉繩固定在貓咪碰不到處，避免繩圈纏繞。',
    source:
        'Zoetis Petcare：How to Cat-Proof Your Home，依公開資料改寫。 https://www.zoetispetcare.com/blog/article/cat-proof-home',
  ),
  PlanetCard(
    id: '139',
    title: '熱天有個涼地方',
    category: '環境與舒適',
    imageAsset: 'assets/cards/139-cat-cool-shade.png',
    petVoice: '太陽熱熱的，我有涼處歇歇。',
    knowledgePoint: '炎熱時提供陰涼通風處與清水，讓貓咪能避開日曬。',
    source:
        'Cats Protection：Cats and Warm Weather，依公開資料改寫。 https://www.cats.org.uk/help-and-advice/home-and-environment/cats-and-warm-weather',
  ),
  PlanetCard(
    id: '140',
    title: '紙箱先檢查',
    category: '探索與安全',
    imageAsset: 'assets/cards/140-cat-safe-box.png',
    petVoice: '小紙箱準備好，讓我探探頭。',
    knowledgePoint: '紙箱先去除膠帶與釘針，保留可自由進出的開口。',
    source:
        'PDSA：Build your own cardboard cat house，依公開資料改寫。 https://www.pdsa.org.uk/what-we-do/blog/build-your-own-cardboard-cat-house',
  ),
];
