// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyATvQYFV6cKOFZzRLrGrh7_-JMYumD90to',
    appId: '1:393735079871:web:b2f33449befc85c5b3430a',
    messagingSenderId: '393735079871',
    projectId: 'fir-project-tw',
    authDomain: 'fir-project-tw.firebaseapp.com',
    storageBucket: 'fir-project-tw.firebasestorage.app',
    measurementId: 'G-3FFW4V2HFH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB6OEU79lB53HZfS2gz2Im-HZ8RDVPTBCQ',
    appId: '1:393735079871:android:fa8b95c9904f8cd7b3430a',
    messagingSenderId: '393735079871',
    projectId: 'fir-project-tw',
    storageBucket: 'fir-project-tw.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCfO12PLUprxxBO4PWyupi-on64pU005vA',
    appId: '1:393735079871:ios:1f59a62298a8d279b3430a',
    messagingSenderId: '393735079871',
    projectId: 'fir-project-tw',
    storageBucket: 'fir-project-tw.firebasestorage.app',
    iosClientId: '393735079871-itjeudch6ga5lph8poobjpjeu36rq0n0.apps.googleusercontent.com',
    iosBundleId: 'com.example.aiPetCommunication',
  );
}
