const fs = require('node:fs');
const path = require('node:path');
const root = path.resolve(__dirname, '..');
const version = fs.readFileSync(path.join(root, 'pubspec.yaml'), 'utf8').match(/^version:\s*(\d+\.\d+\.\d+(?:\+[\w.]+)?)\s*$/m)?.[1];
if (!version) throw Error('Missing or invalid pubspec version');
const outputs = {
  'lib/app/app_version.g.dart': `// Generated by scripts/generate_version.cjs. Edit pubspec.yaml.\nconst appVersion = '${version}';\n`,
};
for (const name of ['index.html', 'flutter_bootstrap.js']) {
  outputs[`web/${name}`] = fs.readFileSync(path.join(root, `tools/build/templates/${name}`), 'utf8')
    .replace(/\r\n/g, '\n').replaceAll('{{APP_VERSION}}', version);
}
for (const [file, content] of Object.entries(outputs)) {
  const target = path.join(root, file);
  if (process.argv.includes('--check')) {
    if (!fs.existsSync(target) || fs.readFileSync(target, 'utf8').replace(/\r\n/g, '\n') !== content) {
      throw Error(`Stale version output: ${file}. Run node scripts/generate_version.cjs`);
    }
  } else {
    fs.mkdirSync(path.dirname(target), {recursive: true});
    fs.writeFileSync(target, content);
  }
}
console.log(`Version verified: ${version}`);
