const fs = require('node:fs');
const path = require('node:path');
const root = path.resolve(__dirname, '..');
const document = JSON.parse(fs.readFileSync(path.join(root, 'content/planet_cards.json'), 'utf8').replace(/^\uFEFF/, ''));
const fields = ['id', 'title', 'category', 'imageAsset', 'petVoice', 'knowledgePoint', 'source'];
if (document.schemaVersion !== 1 || !Array.isArray(document.cards) || !document.cards.length) {
  throw Error('Invalid catalog schema');
}
const images = new Set();
for (const [index, card] of document.cards.entries()) {
  if (Object.keys(card).length !== fields.length || fields.some(key => typeof card[key] !== 'string' || !card[key].trim())) {
    throw Error(`Invalid catalog entry ${index + 1}`);
  }
  if (card.id !== String(index + 1).padStart(3, '0')) throw Error('Card IDs must remain sequential and stable');
  if (!/^assets\/cards\/[A-Za-z0-9_-]+\.png$/.test(card.imageAsset) || !fs.existsSync(path.join(root, card.imageAsset))) {
    throw Error(`Missing or invalid card image: ${card.id}`);
  }
  if (images.has(card.imageAsset)) throw Error(`Duplicate image: ${card.id}`);
  images.add(card.imageAsset);
}
const quote = value => JSON.stringify(value).replace(/\$/g, '\\$');
const generated = '// Generated by scripts/generate_catalog.cjs. Edit content/planet_cards.json.\n' +
  '// dart format off\n' +
  "import '../planet_card_model.dart';\n\nconst planetCards = <PlanetCard>[\n" +
  document.cards.map(card => '  PlanetCard(\n' + fields.map(key => `    ${key}: ${quote(card[key])},\n`).join('') + '  ),\n').join('') +
  '];\n';
const target = path.join(root, 'lib/features/planet/domain/generated/planet_cards.g.dart');
if (process.argv.includes('--check')) {
  if (!fs.existsSync(target) || fs.readFileSync(target, 'utf8').replace(/\r\n/g, '\n') !== generated) {
    throw Error('Catalog output is stale. Run node scripts/generate_catalog.cjs');
  }
} else {
  fs.mkdirSync(path.dirname(target), {recursive: true});
  fs.writeFileSync(target, generated);
}
console.log(`Catalog verified: ${document.cards.length} cards`);
